name: 新功能请求
title: '[Feature] '
description: 请求增加新功能
body:
  - type: markdown
    attributes:
      value: |
        ## 在提交issue之前，请您务必完成以下操作，否则你的issue可能会根据情况直接被关闭！！！
        ## 在提交issue之前，请您务必完成以下操作，否则你的issue可能会根据情况直接被关闭！！！
        ## 在提交issue之前，请您务必完成以下操作，否则你的issue可能会根据情况直接被关闭！！！

        1. 请确认当前并未存在该功能，且没有请求增加该功能的issue
        2. 如果你的issue被受理，受理者提出的问题、要求，应在3日内予以回复，否则会被关闭
        3. 上传文件时请等待文件名前面的 Uploading 消失后再提交，否则文件将会上传失败
  - type: textarea
    id: feature-description
    attributes:
      label: |
        请描述你对功能的想法
      description: |
        这有助于维护者快速了解你的想法，并决定是否增加。

        如果条件允许，最好附带效果图或概念图
    validations:
      required: true