name: beta-release
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3

      - name: build
        run: |
          pnpm install
          pnpm build:beta

      - name: Create Prerelease
        id: create_prerelease
        uses: softprops/action-gh-release@v2
        with:
          name: Beta
          files: ./dist/make-gkd_inspect-better.user.js
          body_path: ./changeLog.md
          prerelease: true
